-- MySQL Script generated by MySQL Workbench
-- 05/23/15 18:08:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema muveo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `muveo` DEFAULT CHARACTER SET utf8 ;
USE `muveo` ;

-- -----------------------------------------------------
-- Table `muveo`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muveo`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `muveo`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nbUsuario` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `tipoUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `nacionalidad` VARCHAR(45) NULL DEFAULT NULL,
  `password` CHAR(128) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `valoracion` INT NULL DEFAULT NULL,
  `formacion` TEXT NULL DEFAULT NULL,
  `avatarPath` VARCHAR(45) NULL DEFAULT NULL,
  `salt` CHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muveo`.`Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muveo`.`Oferta` ;

CREATE TABLE IF NOT EXISTS `muveo`.`Oferta` (
  `idOferta` INT NOT NULL,
  `idOfertante` INT NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `categoria` VARCHAR(45) NULL DEFAULT NULL,
  `localizacion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaPublicacion` DATE NULL DEFAULT NULL,
  `precio` DECIMAL(6,2) NULL DEFAULT NULL,
  `idioma` VARCHAR(45) NULL DEFAULT NULL,
  `valoracion` INT NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL,
  `portadaPath` VARCHAR(45) NULL,
  PRIMARY KEY (`idOferta`),
  INDEX `idOfertante_idx` (`idOfertante` ASC),
  CONSTRAINT `fk_idOfertante`
    FOREIGN KEY (`idOfertante`)
    REFERENCES `muveo`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muveo`.`Contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muveo`.`Contrato` ;

CREATE TABLE IF NOT EXISTS `muveo`.`Contrato` (
  `idUsuario` INT NOT NULL,
  `idOferta` INT NOT NULL,
  `fechaContratacion` DATE NULL DEFAULT NULL,
  `valoracion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`, `idOferta`),
  INDEX `fk_Usuario_has_Oferta_Oferta1_idx` (`idOferta` ASC),
  INDEX `fk_Usuario_has_Oferta_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Oferta_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `muveo`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Oferta_Oferta1`
    FOREIGN KEY (`idOferta`)
    REFERENCES `muveo`.`Oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muveo`.`Etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muveo`.`Etiqueta` ;

CREATE TABLE IF NOT EXISTS `muveo`.`Etiqueta` (
  `idEtiqueta` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEtiqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muveo`.`EtiquetasOferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muveo`.`EtiquetasOferta` ;

CREATE TABLE IF NOT EXISTS `muveo`.`EtiquetasOferta` (
  `idOferta` INT NOT NULL,
  `idEtiqueta` INT NOT NULL,
  PRIMARY KEY (`idOferta`, `idEtiqueta`),
  INDEX `fk_Oferta_has_Etiqueta_Etiqueta1_idx` (`idEtiqueta` ASC),
  INDEX `fk_Oferta_has_Etiqueta_Oferta1_idx` (`idOferta` ASC),
  CONSTRAINT `fk_Oferta_has_Etiqueta_Oferta1`
    FOREIGN KEY (`idOferta`)
    REFERENCES `muveo`.`Oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_has_Etiqueta_Etiqueta1`
    FOREIGN KEY (`idEtiqueta`)
    REFERENCES `muveo`.`Etiqueta` (`idEtiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `muveo`.`LoginAttempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `muveo`.`LoginAttempt` ;

CREATE TABLE IF NOT EXISTS `muveo`.`LoginAttempt` (
  `idAttempt` INT NOT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idAttempt`),
  INDEX `fk_idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `muveo`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
